[package]
name = "screen_capure_marco"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-sidecar = "1.1.0"
anyhow = "1.0.86"
iced = { version = "0.10.0", features = ["wgpu"] }
winit = "0.30.5"
winapi = "0.3.9"
global-hotkey = "0.6.2"